# Generated by Django 4.0.3 on 2022-05-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_delete_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=32, unique=True)),
                ('mounted', models.BooleanField(default=False)),
            ],
        ),
    ]
