# Generated by Django 4.0.3 on 2022-05-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_horse_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
