# Generated by Django 4.0.3 on 2022-06-11 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('date_of_birth', models.DateField()),
                ('degree_of_difficulty', models.TextField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('diagnosis', models.ManyToManyField(blank=True, related_name='condition', to='administration.diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participates', to='hippotherapy.client')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'ordering': ['size'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('session_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='hippotherapy.course')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ridden', to='administration.horse')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=32, unique=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functional_skill', to='hippotherapy.function')),
            ],
        ),
        migrations.CreateModel(
            name='SkillScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_session', to='hippotherapy.session')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_skill', to='hippotherapy.skill')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='skill',
            field=models.ManyToManyField(related_name='skill_score', through='hippotherapy.SkillScore', to='hippotherapy.skill'),
        ),
        migrations.AddField(
            model_name='session',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='performed', to='administration.task'),
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_name', models.TextField()),
                ('order_in_skill', models.IntegerField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_hint', to='hippotherapy.skill')),
            ],
            options={
                'ordering': ['skill', 'order_in_skill'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='hat_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wears', to='hippotherapy.hat'),
        ),
    ]
