# Generated by Django 4.0.3 on 2022-05-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippotherapy', '0002_function_alter_hat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hint',
            options={'ordering': ['skill', 'order_in_skill']},
        ),
        migrations.AddField(
            model_name='hint',
            name='order_in_skill',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
