# Generated by Django 4.0.3 on 2022-05-06 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_task_task_name'),
        ('hippotherapy', '0003_alter_hint_options_hint_order_in_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participates', to='hippotherapy.client')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('session_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_course', to='hippotherapy.course')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ridden', to='administration.horse')),
                ('skills', models.ManyToManyField(null=True, related_name='skill_score', to='hippotherapy.skill')),
                ('tasks', models.ManyToManyField(related_name='performed', to='administration.task')),
            ],
        ),
    ]
