# Generated by Django 4.0.3 on 2022-05-13 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_task_task_name'),
        ('hippotherapy', '0004_course_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='skills',
            field=models.ManyToManyField(related_name='skill_score', to='hippotherapy.skill'),
        ),
        migrations.AlterField(
            model_name='session',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='performed', to='administration.task'),
        ),
        migrations.CreateModel(
            name='SkillScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_session', to='hippotherapy.session')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_skill', to='hippotherapy.skill')),
            ],
        ),
    ]
