# Generated by Django 4.0.3 on 2022-05-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippotherapy', '0006_skillxscore_remove_session_skills_session_skillx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='skill',
            field=models.ManyToManyField(related_name='skill_score', through='hippotherapy.SkillScore', to='hippotherapy.skill'),
        ),
        migrations.AlterField(
            model_name='session',
            name='skillx',
            field=models.ManyToManyField(related_name='skill_x_score', through='hippotherapy.SkillxScore', to='hippotherapy.skill'),
        ),
    ]
