# Generated by Django 4.0.3 on 2022-05-21 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_alter_diagnosis_diagnosis'),
        ('hippotherapy', '0009_remove_session_skillx_delete_skillxscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='diagnosis',
            field=models.ManyToManyField(blank=True, null=True, related_name='condition', to='administration.diagnosis'),
        ),
        migrations.AlterField(
            model_name='session',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='hippotherapy.course'),
        ),
    ]
