# Generated by Django 4.0.3 on 2022-05-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_alter_diagnosis_diagnosis'),
        ('hippotherapy', '0010_alter_client_diagnosis_alter_session_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='diagnosis',
            field=models.ManyToManyField(blank=True, related_name='condition', to='administration.diagnosis'),
        ),
    ]
