# Generated by Django 4.0.3 on 2022-06-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippotherapy', '0011_alter_client_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
